"""L247 - build optimizer_l247probe.py: instrument the REPAIR ROUNDS.

43% of all LP builds are repair rounds (21 cases -> 37 builds at the shipped
prune_B=8), and every one of them rebuilds AND re-solves the whole program with
nothing changed but `force_keep`. If the terms that end up being forced could be
predicted and included in round 1, rounds collapse toward 1.0 and both halves of
the LP -- the 25% Python and the 75% solver -- drop by the same 43%.

Correctness is free either way: solve_pruned VERIFIES every dropped term's
assumed sign after the solve and forces the offenders back, so over-predicting
costs a few rows and under-predicting costs exactly the round it costs today.
That is why this is worth measuring before it is worth building.

THE CANDIDATE PREDICTOR, available before any solve: a term is dropped when
`|dC| > slack`, so `margin = |dC| - slack` is how far it cleared the threshold.
The realized `delta` is bounded by roughly that same slack, so terms that barely
cleared should be the ones whose sign actually flips. This probe records, per
case and round, every dropped term's margin and which tids were forced, so the
question "do the forced terms live in the small-margin tail?" is answered with
data rather than with that paragraph.

Diagnostic only. Never shipped.

  <python> l247_patch.py
"""
import pathlib
import sys

SRC = pathlib.Path("optimizer_constructive.py")
DST = pathlib.Path("optimizer_l247probe.py")

PATCHES = [
    # 1. carry `slack` on every dropped term so the margin is recoverable
    ('''            dropped.append((tid, lin, dC, wsc))   # lin is already a tuple
            return''',
     '''            dropped.append((tid, lin, dC, wsc, slack))  # L247: + slack
            return'''),
    # 2. solve_pruned unpacks 5 now, and records what it forced
    ('''        x = res.x
        bad = set()
        for tid, lin, dC, _w in d["prune_dropped_terms"]:
            delta = 0.0
            for col, coef in lin:
                delta += coef * x[col]
            # assumed sgn(dC); violated iff the true value took the other branch
            if (dC + delta) * (1.0 if dC > 0.0 else -1.0) < -1e-12:
                bad.add(tid)
        if not bad:
            d["prune_rounds"] = rnd + 1
            return d, rnd + 1
        keep |= bad''',
     '''        x = res.x
        bad = set()
        _margins = {}
        for tid, lin, dC, _w, _slack in d["prune_dropped_terms"]:
            delta = 0.0
            for col, coef in lin:
                delta += coef * x[col]
            _margins[tid] = abs(dC) - _slack
            # assumed sgn(dC); violated iff the true value took the other branch
            if (dC + delta) * (1.0 if dC > 0.0 else -1.0) < -1e-12:
                bad.add(tid)
        _L247.append({"ci": ci, "round": rnd, "n_dropped": len(_margins),
                      "n_kept": d["prune_kept"], "bad": sorted(bad),
                      "margins": _margins, "forced_in": sorted(keep)})
        if not bad:
            d["prune_rounds"] = rnd + 1
            return d, rnd + 1
        keep |= bad'''),
]

HDR = ('"""L247 PROBE COPY -- NEVER SHIPPED. Records repair-round structure in\n'
       '_L247; generated by l247_patch.py."""\n'
       '_L247 = []\n\n\n')


def main():
    s = SRC.read_text(encoding="utf-8")
    for old, new in PATCHES:
        c = s.count(old)
        if c != 1:
            print("!! patch matched {} times: {!r}".format(c, old[:70]))
            return 1
        s = s.replace(old, new)
    DST.write_text(HDR + s, encoding="utf-8", newline="\n")
    print("wrote {} ({} bytes)".format(DST, DST.stat().st_size))
    return 0


if __name__ == "__main__":
    sys.exit(main())
