"""L248 - build optimizer_l248probe.py: a SIZE-LIMITED lens-D tier.

L167 killed the 32-vector tier and L232 re-measured it today: quality
+0.5596% in set, case wall 1.413x, NET -2.613%. Both measured ONLY the full 32.
The curve between 0 and 32 has never been measured, and there is a structural
reason to expect it is not linear:

  the 48-core pool is MAX-SETTER bound until sum(d_p)/48 exceeds max(d_p).
  Measured on the shipped tree at n=120: sum/48 = 2.501 s against d_max =
  3.204 s, so the crossover is at 51 x (3.204/2.501) = ~65 profiles. Below it,
  an added profile costs (almost) nothing in C++ wall; above it, every added
  profile costs 1/48 of its own duration on the critical path.

So the first ~14 additions sit in a different cost regime from the last 18, and
the whole tier was priced at a point past the crossover. If quality is roughly
linear in the count while cost has a knee at 65, there may be a net-positive
prefix that nobody has looked at.

ICCAD_LENSD_K=<n> takes the first n vectors (the list is UNORDERED random
sampling -- L167 chose uniform random precisely so there is no in-sample fitting
in the pick -- so a prefix is as unbiased as the whole).

Diagnostic only. Never shipped.

  <python> l248_patch.py
"""
import pathlib
import sys

SRC = pathlib.Path("optimizer_constructive.py")
DST = pathlib.Path("optimizer_l248probe.py")

OLD = '''def _lensd_active(block_count: int) -> FrozenSet[int]:
    """Probe tier, OFF unless ICCAD_LENSD_POOL=1. Read at CALL time."""
    if os.environ.get("ICCAD_LENSD_POOL", "0") != "1":
        return frozenset()
    return _LENSD_IDX'''

NEW = '''def _lensd_active(block_count: int) -> FrozenSet[int]:
    """Probe tier, OFF unless ICCAD_LENSD_POOL=1. Read at CALL time.

    L248: ICCAD_LENSD_K=<n> takes the first n vectors, so the cost/quality curve
    can be measured on both sides of the max-bound -> sum-bound crossover
    (~65 profiles) instead of only at the far end."""
    if os.environ.get("ICCAD_LENSD_POOL", "0") != "1":
        return frozenset()
    _k = os.environ.get("ICCAD_LENSD_K", "")
    if _k:
        try:
            k = max(0, min(len(_LENSD_EXTRA), int(_k)))
        except ValueError:
            return _LENSD_IDX
        return frozenset(range(_LENSD_BASE, _LENSD_BASE + k))
    return _LENSD_IDX'''


def main():
    s = SRC.read_text(encoding="utf-8")
    if s.count(OLD) != 1:
        print("!! anchor matched {} times".format(s.count(OLD)))
        return 1
    hdr = ('"""L248 PROBE COPY -- NEVER SHIPPED. Adds ICCAD_LENSD_K to size the\n'
           'lens-D tier; generated by l248_patch.py."""\n')
    DST.write_text(hdr + s.replace(OLD, NEW), encoding="utf-8", newline="\n")
    print("wrote {} ({} bytes)".format(DST, DST.stat().st_size))
    return 0


if __name__ == "__main__":
    sys.exit(main())
